### ISSUE TITLE
Can I suppress debug output?

### ISSUE THREAD

**Issue by yukilabo** [DrAma999/LittleBlueTooth#16]
When I use LittleBlueTooth to communicate with a device periodically, the combine debug print fills up the console.
Is it possible to turn on/off the debug output?

**Comment by DrAma999** [comment]
Hello there @yukilabo,
depends.
There are 3 types of log:

- Log (based on os_log) that is activated by using the property `isLogEnabled` in the configuration class. Its default is `false` and if you are seeing some of them is a bug and I need to fix it
- Combine `print` operator in the combine pipeline. I need to make some considerations or replace them with something that can be disabled, because they are pretty useful, but I can understand that with notifications active they can be to much
- `print` functions that appears randomly in code and that are leftovers from developing. They majority of them must be removed.

On the other hand you can safely fork the project and delete them.

I will try to figure out something this week end :-)

Best,
Andrea

**Comment by DrAma999** [comment]
So it seemed to be easier than I though.
Now all log are disabled by default, if you want to enable them just set the property `isLogEnabled` in the configuration object before passing to LittleBluetooth instance. Just update the project.

**Comment by yukilabo** [comment]
Thank you so much for modify log system!

**Comment by DrAma999** [comment]
> Thank you so much for modify log system!

Arigato gozaimasu for using my library :-D
